### ISSUE TITLE
simple tester should flag missing annotation property binding

### ISSUE THREAD

**Issue by matentzn** [INCATools/dead_simple_owl_design_patterns#54]
```
annotations:
  - annotationProperty: oio:hasExactSynonym
    text: "acquired %s"
    vars:
     - disease
```

I dont know why, but this all by itself is rejected by dosdp tools (so I assume the spec rejects this)

This is accepted:

```
annotationProperties:
  exact_synonym: oio:hasExactSynonym 

annotations:
  - annotationProperty: exact_synonym
    text: "acquired %s"
    vars:
     - disease
```

@dosumis can you confirm which is at fault, the spec or DOSDP tools?

**Comment by dosumis** [comment]
Properties, like classes, need to be declared before they are used.

There's a simpler built-in short cut for oio APs corresponding to OBO tags though.  You can just use one of these tags directly:

https://github.com/INCATools/dead_simple_owl_design_patterns/blob/master/spec/DOSDP_schema_full.yaml#L353.  

Value can be a list of strings.

**Comment by matentzn** [comment]
Ok! Then we need to make sure that simple-tester warns about the first case! Right now, they are ignored

**Comment by matentzn** [comment]
Along the same lines, we need to be warned of this case:

```
classes:
    acquired: MONDO:0021141

vars:
    disease: owl:Thing
```

(a VAR referring to something that is not declared in classes.
