### ISSUE TITLE
Need QC for %s

### ISSUE THREAD

**Issue by matentzn** [INCATools/dead_simple_owl_design_patterns#56]
One of the most important pain points during validation is cases when I am using `%` instead of `%s` in pattern strings strings. Example:

```
name:
  text: "% adenoma"
  vars:
    - v0

def:
  text: "A adenoma that involves the %."
  vars:
    - v0
```

This should be carefully QCed, by taking also into account the number of variables in the subsequent `vars` section; This could avoid mistakenly flagging up cases like like

```
def:
  text: "A adenoma that involves at least 90% the %s."
  vars:
    - v0
```

or

```
def:
  text: "A adenoma that involves at least 90 % the %s."
  vars:
    - v0
```
