### ISSUE TITLE
New method request: dosdp normalise

### ISSUE THREAD

**Issue by matentzn** [INCATools/dead_simple_owl_design_patterns#80]
We need a method in dosdp which takes in a dosdp yaml file an returns it in a nicely canonical form:

- [ ] canonical ordering of elements
- [ ] canonical use of quotes in strings, in particular avoiding `'''`
- [ ] canonical rendering of block strings

**Comment by matentzn** [comment]
We will use the ordering directly from the json schema, its perfect:

https://github.com/INCATools/dead_simple_owl_design_patterns/blob/master/src/schema/dosdp_schema.yaml#L299

Test data (bad examples):
https://github.com/monarch-initiative/mondo/tree/master/src/patterns/dosdp-patterns

Good example (mostly good):
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml

I used this script back in the days:

- [ ] canonical indentation (2 space)
- [ ] Deal with large multi-line text ([example](https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/acquired.yaml#L5))
- [ ] Canonicalise order of sub-elements (https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml#L37), but NEVER `vars`
- [ ] Canonicalise spaceing between elements (https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml#L4) - probably really difficult. If

**Comment by matentzn** [comment]
@dosumis any chance we can have @hkir-dev work on that, if he wants?

**Comment by hkir-dev** [comment]
Hi Nico, yes this is in my todo list. You can assign it to me.

**Comment by hkir-dev** [comment]
I faced some issues while ordering comments. Ruamel.yaml is associating comments with the preceding element (https://stackoverflow.com/a/42173906). Based on the context, this behavior sometimes make sense, but sometimes cause confusion. For example:

```
relations:
  part_of: "BFO:0000050"
#  in_taxon: "RO:0002162"

# My comment on vars is ....
vars:
  gross_cell_type: "'cell'"
```

So in this case both comments belong to `relations`. If I change order of the `relations` or `vars`, "My comment on vars is ...." is sticking with the `relations`.

```
vars:
  gross_cell_type: "'cell'"

relations:
  part_of: "BFO:0000050"
#  in_taxon: "RO:0002162"

# My comment on vars is ....
```

Do you have any suggestions for the fix. Or, we can release the initial version as is (just warn user to check comments in the pattern file) and try to fix this issue in later versions.
