### ISSUE TITLE
Validator does not check annotationProperty bindings

### ISSUE THREAD

**Issue by matentzn** [INCATools/dead_simple_owl_design_patterns#82]
If I have this:

```
annotations: 
  - annotationProperty: exact_synonym
    text: "%s %s"
    vars:
      - location
      - attribute
```

but not this:

```
annotationProperties:
  exact_synonym: oio:hasExactSynonym
  related_synonym: oio:hasRelatedSynonym
```

Validation passes.
