### ISSUE TITLE
Examples and tags wrong type

### ISSUE THREAD

**Issue by hkir-dev** [INCATools/dead_simple_owl_design_patterns#83]
Type of the examples and tags are wrong in the dosdp chema. `list` should be changed to `array`.

CI should validate dosdp schema before merge.

```yaml
  examples:
    type: list
    items: { type: string }
    description:  "A list of example terms implementing this pattern."
    doc_type: root
```
